const SET_COLOR = 'SET_COLOR';
const SET_ACTIVE_TOOL = 'SET_ACTIVE_TOOL';
const SET_PEN_SIZE = 'SET_PEN_SIZE';
const UPDATE_FRAME = 'UPDATE_FRAME';
const SET_CURRENT_FRAME = 'SET_CURRENT_FRAME';
const ADD_FRAME = 'ADD_FRAME';
const DELETE_FRAME = 'DELETE_FRAME';

export {
  SET_COLOR,
  SET_ACTIVE_TOOL,
  SET_PEN_SIZE,
  UPDATE_FRAME,
  SET_CURRENT_FRAME,
  ADD_FRAME,
  DELETE_FRAME,
};
