const SET_COLOR = 'SET_COLOR';
const SET_ACTIVE_TOOL = 'SET_ACTIVE_TOOL';
const SET_PEN_SIZE = 'SET_PEN_SIZE';
const UPDATE_FRAME = 'UPDATE_FRAME';
const REARRANGE_FRAMES = 'REARRANGE_FRAMES';
const SET_CURRENT_FRAME = 'SET_CURRENT_FRAME';
const ADD_FRAME = 'ADD_FRAME';
const DELETE_FRAME = 'DELETE_FRAME';
const UPDATE_BUTTON = 'UPDATE_BUTTON';
const CHANGE_FRAMERATE = 'CHANGE_FRAMERATE';
const FRAME = 'frame';

export {
  SET_COLOR,
  SET_ACTIVE_TOOL,
  SET_PEN_SIZE,
  FRAME,
  UPDATE_FRAME,
  REARRANGE_FRAMES,
  CHANGE_FRAMERATE,
  SET_CURRENT_FRAME,
  ADD_FRAME,
  DELETE_FRAME,
  UPDATE_BUTTON,
};
